# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test_PCCS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'GoogleMaps'
pod 'IQKeyboardManagerSwift', '5.0.0'

  # Pods for Test_PCCS

  target 'Test_PCCSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test_PCCSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
